baseURL = "https://yabertz.site/"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "Iyas Mawardi"
enableRobotsTXT = true
enableEmoji = true
summaryLength = 28
enableGitInfo = true
disablePathToLower = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "kategori"

[permalinks]
  artikel = "/artikel/:slug/"
  cerita = "/cerita/:slug/"
  buletin = "/buletin/:slug/"
[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookSection = "*"
  BookDateFormat = "2 January 2006"
  BookComments = false
  BookPortableLinks = true
  BookServiceWorker = false

[menu]
  [[menu.main]]
    name = "Artikel"
    pageRef = "/artikel"
    weight = 10
  [[menu.main]]
    name = "Cerita"
    pageRef = "/cerita"
    weight = 20
  [[menu.main]]
    name = "Buletin"
    pageRef = "/buletin"
    weight = 30
  [[menu.main]]
    name = "Tentang"
    pageRef = "/tentang"
    weight = 40

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[caches]
  [caches.images]
    dir = ":cacheDir/images"
